### ISSUE TITLE
How to change background behind icons

### ISSUE THREAD

**Issue by zerostatic** [jkphl/gulp-svg-sprite#83] opened 2018-08-13 20:54 UTC
I asked the same question in the svg-sprite repo, but since I'm using this gulp version, it might be better asked here:

Could you show a simple example of how to change the background (checkerboard) pattern that is behind each icon?

**Comment by jkphl** [comment] 2018-08-15 21:04
Duplicate of https://github.com/jkphl/svg-sprite/issues/273

**Closed by jkphl** 2018-08-15 21:04 UTC
